In [264]:
import pandas as pd
import numpy as np

students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 108],
    "name": [
        "Alex", "Max", "Anna", "Kate", "John",
        "Mike", "Lisa", "Tom", "Tom"
    ],
    "age": [19, 21, 18, 20, None, 23, 19, 24, 24],
    "city": [
        "Moscow", "Berlin", "Moscow", "Paris", "Berlin",
        "Moscow", "Paris", "Berlin", "Berlin"
    ]
})

results = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 108],
    "score": [72, 85, 91, 58, 67, None, 49],
    "hours": [4, 6, 7, 3, 5, 6, 2],
    "passed": [1, 1, 1, 0, 0, 1, 0]
})

courses = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "course": [
        "ML", "ML", "ML", "Python",
        "Python", "ML", "Python", "Python"
    ]
})

In [265]:
students.head(5)

   student_id  name   age    city
0         101  Alex  19.0  Moscow
1         102   Max  21.0  Berlin
2         103  Anna  18.0  Moscow
3         104  Kate  20.0   Paris
4         105  John   NaN  Berlin

In [266]:
students.tail(3)

   student_id  name   age    city
6         107  Lisa  19.0   Paris
7         108   Tom  24.0  Berlin
8         108   Tom  24.0  Berlin

In [267]:
students.shape

(9, 4)

In [268]:
students.columns

Index(['student_id', 'name', 'age', 'city'], dtype='str')

In [269]:
students.dtypes

student_id      int64
name              str
age           float64
city              str
dtype: object

In [270]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  9 non-null      int64
 1   name        9 non-null      str
 2   age         8 non-null      float64
 3   city        9 non-null      str
dtypes: float64(1), int64(1), str(2)
memory usage: 420.0 bytes

In [271]:
students.describe()

       student_id        age
count    9.000000   8.000000
mean   104.888889  21.000000
std      2.571208   2.390457
min    101.000000  18.000000
25%    103.000000  19.000000
50%    105.000000  20.500000
75%    107.000000  23.250000
max    108.000000  24.000000

Потому что там есть пропуск

In [272]:
students_name = students["name"]
students_data_1 = students[["name", "city"]]
students_data_2 = students.iloc[:5, :4]
students_data_3 = students.iloc[1:5, 1:]

In [273]:
students_young = students[(students["age"] < 21) & (students["city"] == "Moscow")]
students_young

   student_id  name   age    city
0         101  Alex  19.0  Moscow
2         103  Anna  18.0  Moscow

In [274]:
students_city = students[(students["city"] == "Moscow") | (students["city"] == "Paris")]
students_city

   student_id  name   age    city
0         101  Alex  19.0  Moscow
2         103  Anna  18.0  Moscow
3         104  Kate  20.0   Paris
5         106  Mike  23.0  Moscow
6         107  Lisa  19.0   Paris

In [275]:
print(students.loc[students["age"] < 21, ["name", "age"]])

   name   age
0  Alex  19.0
2  Anna  18.0
3  Kate  20.0
6  Lisa  19.0

In [276]:
students.isna().sum()

student_id    0
name          0
age           1
city          0
dtype: int64

In [277]:
students_clean = students.copy()
students_clean["age"] = students_clean["age"].fillna(students["age"].mean())
students_clean

   student_id  name   age    city
0         101  Alex  19.0  Moscow
1         102   Max  21.0  Berlin
2         103  Anna  18.0  Moscow
3         104  Kate  20.0   Paris
4         105  John  21.0  Berlin
5         106  Mike  23.0  Moscow
6         107  Lisa  19.0   Paris
7         108   Tom  24.0  Berlin
8         108   Tom  24.0  Berlin

In [278]:
students_clean.isna().sum()

student_id    0
name          0
age           0
city          0
dtype: int64

In [279]:
students_clean.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
dtype: bool

In [280]:
students_dublicated_string = students_clean[students_clean.duplicated()]
print(students_dublicated_string)

   student_id name   age    city
8         108  Tom  24.0  Berlin

In [281]:
students_clean = students_clean.iloc[:8,:]
students_clean

   student_id  name   age    city
0         101  Alex  19.0  Moscow
1         102   Max  21.0  Berlin
2         103  Anna  18.0  Moscow
3         104  Kate  20.0   Paris
4         105  John  21.0  Berlin
5         106  Mike  23.0  Moscow
6         107  Lisa  19.0   Paris
7         108   Tom  24.0  Berlin

In [282]:
students_clean.shape

(8, 4)

Потому что именя могут повторяться, а айди уникален

In [283]:
df_inner = students_clean.merge(results, on="student_id", how="inner")
df_inner

   student_id  name   age    city  score  hours  passed
0         101  Alex  19.0  Moscow   72.0      4       1
1         102   Max  21.0  Berlin   85.0      6       1
2         103  Anna  18.0  Moscow   91.0      7       1
3         104  Kate  20.0   Paris   58.0      3       0
4         105  John  21.0  Berlin   67.0      5       0
5         106  Mike  23.0  Moscow    NaN      6       1
6         108   Tom  24.0  Berlin   49.0      2       0

In [284]:
df_left = students_clean.merge(results, on="student_id", how="left")
df_left

   student_id  name   age    city  score  hours  passed
0         101  Alex  19.0  Moscow   72.0    4.0     1.0
1         102   Max  21.0  Berlin   85.0    6.0     1.0
2         103  Anna  18.0  Moscow   91.0    7.0     1.0
3         104  Kate  20.0   Paris   58.0    3.0     0.0
4         105  John  21.0  Berlin   67.0    5.0     0.0
5         106  Mike  23.0  Moscow    NaN    6.0     1.0
6         107  Lisa  19.0   Paris    NaN    NaN     NaN
7         108   Tom  24.0  Berlin   49.0    2.0     0.0

In [285]:
full_df = df_left.merge(courses, on="student_id", how="left")
full_df

   student_id  name   age    city  score  hours  passed  course
0         101  Alex  19.0  Moscow   72.0    4.0     1.0      ML
1         102   Max  21.0  Berlin   85.0    6.0     1.0      ML
2         103  Anna  18.0  Moscow   91.0    7.0     1.0      ML
3         104  Kate  20.0   Paris   58.0    3.0     0.0  Python
4         105  John  21.0  Berlin   67.0    5.0     0.0  Python
5         106  Mike  23.0  Moscow    NaN    6.0     1.0      ML
6         107  Lisa  19.0   Paris    NaN    NaN     NaN  Python
7         108   Tom  24.0  Berlin   49.0    2.0     0.0  Python

In [286]:
full_df.groupby("city").agg({
    "score":["mean", "min"],
    "hours":["mean", "sum"]
})

       score           hours
        mean   min      mean   sum
city
Berlin  67.0  49.0  4.333333  13.0
Moscow  81.5  72.0  5.666667  17.0
Paris   58.0  58.0  3.000000   3.0

In [287]:
full_df.groupby(["city","course"])["score"].mean()

city    course
Berlin  ML        85.0
        Python    58.0
Moscow  ML        81.5
Paris   Python    58.0
Name: score, dtype: float64

In [288]:
def get_level(x):
    if pd.isna(x):
        return "unknown"
    elif x >= 85:
        return "excellent"
    elif x >= 70:
        return "good"
    else:
        return "bad"

In [289]:
full_df["level"] = full_df["score"].apply(get_level)
full_df

   student_id  name   age    city  score  hours  passed  course      level
0         101  Alex  19.0  Moscow   72.0    4.0     1.0      ML       good
1         102   Max  21.0  Berlin   85.0    6.0     1.0      ML  excellent
2         103  Anna  18.0  Moscow   91.0    7.0     1.0      ML  excellent
3         104  Kate  20.0   Paris   58.0    3.0     0.0  Python        bad
4         105  John  21.0  Berlin   67.0    5.0     0.0  Python        bad
5         106  Mike  23.0  Moscow    NaN    6.0     1.0      ML    unknown
6         107  Lisa  19.0   Paris    NaN    NaN     NaN  Python    unknown
7         108   Tom  24.0  Berlin   49.0    2.0     0.0  Python        bad

In [290]:
full_df["hours_squared"] = full_df["hours"] ** 2
full_df

,student_id,name,age,city,score,hours,passed,course,level,hours_squared
0,101,Alex,19.0,Moscow,72.0,4.0,1.0,ML,good,16.0
1,102,Max,21.0,Berlin,85.0,6.0,1.0,ML,excellent,36.0
2,103,Anna,18.0,Moscow,91.0,7.0,1.0,ML,excellent,49.0
3,104,Kate,20.0,Paris,58.0,3.0,0.0,Python,bad,9.0
4,105,John,21.0,Berlin,67.0,5.0,0.0,Python,bad,25.0
5,106,Mike,23.0,Moscow,NaN,6.0,1.0,ML,unknown,36.0
6,107,Lisa,19.0,Paris,NaN,NaN,NaN,Python,unknown,NaN
7,108,Tom,24.0,Berlin,49.0,2.0,0.0,Python,bad,4.0

In [291]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5, 6],
    "name": ["Alex", "Max", "Anna", "Kate", "John", "Lisa"],
    "department": ["IT", "IT", "Sales", "Sales", "IT", "Sales"]
})

performance = pd.DataFrame({
    "employee_id": [1, 2, 3, 4, 5],
    "tasks": [15, 8, 20, 11, 18],
    "rating": [4.8, 3.2, 4.5, 2.9, 4.1]
})

In [292]:
full_df = employees.merge(performance, on="employee_id", how = "left")
full_df

   employee_id  name department  tasks  rating
0            1  Alex         IT   15.0     4.8
1            2   Max         IT    8.0     3.2
2            3  Anna      Sales   20.0     4.5
3            4  Kate      Sales   11.0     2.9
4            5  John         IT   18.0     4.1
5            6  Lisa      Sales    NaN     NaN

In [293]:
full_df.groupby("department")["rating"].agg(["mean", "min", "max"])

                mean  min  max
department
IT          4.033333  3.2  4.8
Sales       3.700000  2.9  4.5

In [294]:
full_df.groupby("department").agg({
    "rating": ["mean", "max"],
    "tasks":["mean", "sum"]
})

              rating           tasks
                mean  max       mean   sum
department
IT          4.033333  4.8  13.666667  41.0
Sales       3.700000  4.5  15.500000  31.0

In [ ]:
def get_status(rating):
    if pd.isna(rating):
        return "unknown"
    elif rating >= 4.5:
        return "excellent"
    elif rating >= 3.5:
        return "good"
    else:
        return "low"

full_df["status"] = full_df["rating"].apply(get_status)
full_df

   employee_id  name department  tasks  rating     status
0            1  Alex         IT   15.0     4.8  excellent
1            2   Max         IT    8.0     3.2        low
2            3  Anna      Sales   20.0     4.5       good
3            4  Kate      Sales   11.0     2.9        low
4            5  John         IT   18.0     4.1       good
5            6  Lisa      Sales    NaN     NaN    unknown

In [297]:
full_df["tasks_double"] = full_df["tasks"] * 2
full_df

   employee_id  name department  tasks  rating     status  tasks_double
0            1  Alex         IT   15.0     4.8  excellent          30.0
1            2   Max         IT    8.0     3.2        low          16.0
2            3  Anna      Sales   20.0     4.5       good          40.0
3            4  Kate      Sales   11.0     2.9        low          22.0
4            5  John         IT   18.0     4.1       good          36.0
5            6  Lisa      Sales    NaN     NaN    unknown           NaN

Потому что лефт сохранит левый датафрейм без изменений, а во втором просто поставит Nan если не будет хватать данных

Потому что нехватало данных

Потому что не зачем нагромождать