In [175]:
import pandas as pd
import numpy as np

students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 108, 109],
    "name": [
        "Alex", "Max", "Anna", "Kate", "John",
        "Mike", "Lisa", "Tom", "Tom", "Emma"
    ],
    "age": [
        19, 21, 18, 20, np.nan,
        23, 19, 24, 24, 22
    ],
    "city": [
        "Moscow", "Berlin", "Moscow", "Paris", "Berlin",
        "Moscow", "Paris", "Berlin", "Berlin", "Moscow"
    ],
    "hours": [
        4, 6, 7, 3, 5,
        np.nan, 8, 2, 2, 6
    ]
})

results = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 108, 109],
    "score": [72, 85, 91, 58, np.nan, 76, 49, 88],
    "passed": [1, 1, 1, 0, 0, 1, 0, 1]
})

courses = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109],
    "course": [
        "ML", "ML", "ML", "Python", "Python",
        "ML", "Python", "Python", "ML"
    ]
})

In [176]:
students.isna().sum()

student_id    0
name          0
age           1
city          0
hours         1
dtype: int64

In [177]:
students.duplicated().sum()

1

In [178]:
students.iloc[students.duplicated()]

   student_id name   age    city  hours
8         108  Tom  24.0  Berlin    2.0

In [179]:
students_clean = students.copy()[~students.duplicated()]
students_clean

   student_id  name   age    city  hours
0         101  Alex  19.0  Moscow    4.0
1         102   Max  21.0  Berlin    6.0
2         103  Anna  18.0  Moscow    7.0
3         104  Kate  20.0   Paris    3.0
4         105  John   NaN  Berlin    5.0
5         106  Mike  23.0  Moscow    NaN
6         107  Lisa  19.0   Paris    8.0
7         108   Tom  24.0  Berlin    2.0
9         109  Emma  22.0  Moscow    6.0

In [180]:
students_clean["age"] = students_clean["age"].fillna(students_clean["age"].median())
students_clean

   student_id  name   age    city  hours
0         101  Alex  19.0  Moscow    4.0
1         102   Max  21.0  Berlin    6.0
2         103  Anna  18.0  Moscow    7.0
3         104  Kate  20.0   Paris    3.0
4         105  John  20.5  Berlin    5.0
5         106  Mike  23.0  Moscow    NaN
6         107  Lisa  19.0   Paris    8.0
7         108   Tom  24.0  Berlin    2.0
9         109  Emma  22.0  Moscow    6.0

In [181]:
students_clean["hours"] = students["hours"].fillna(students_clean["hours"].median()).copy()
students_clean

   student_id  name   age    city  hours
0         101  Alex  19.0  Moscow    4.0
1         102   Max  21.0  Berlin    6.0
2         103  Anna  18.0  Moscow    7.0
3         104  Kate  20.0   Paris    3.0
4         105  John  20.5  Berlin    5.0
5         106  Mike  23.0  Moscow    5.5
6         107  Lisa  19.0   Paris    8.0
7         108   Tom  24.0  Berlin    2.0
9         109  Emma  22.0  Moscow    6.0

In [182]:
students_clean_new_data_1 = students_clean.iloc[:4, :3]
students_clean_new_data_2 = students_clean.loc[students_clean.index[2:6],["name", "age", "city"]].copy()

In [183]:
students_clean_new_data_2

   name   age    city
2  Anna  18.0  Moscow
3  Kate  20.0   Paris
4  John  20.5  Berlin
5  Mike  23.0  Moscow

In [184]:
mask = students_clean["age"] < 21
students_new_data_young = students_clean[mask].copy()

In [185]:
mask_2 = (students_clean["city"] == "Moscow") | (students_clean["city"] == "Paris")
students_new_data_city = students_clean[mask_2].copy()

In [186]:
mask_3 = (students_clean["city"] == "Moscow") & (students_clean["hours"] >= 6)
students_clean_new_data_3 = students_clean[mask_3].copy()

In [187]:
mask_4 = students_clean["hours"] >= 6
students_clean_new_data_4 = students_clean.loc[mask_4, ["name", "city", "hours"]].copy()

In [188]:
full_df = students_clean.merge(results, on="student_id", how="left").merge(courses, on="student_id", how="left")
full_df

   student_id  name   age    city  hours  score  passed  course
0         101  Alex  19.0  Moscow    4.0   72.0     1.0      ML
1         102   Max  21.0  Berlin    6.0   85.0     1.0      ML
2         103  Anna  18.0  Moscow    7.0   91.0     1.0      ML
3         104  Kate  20.0   Paris    3.0   58.0     0.0  Python
4         105  John  20.5  Berlin    5.0    NaN     0.0  Python
5         106  Mike  23.0  Moscow    5.5   76.0     1.0      ML
6         107  Lisa  19.0   Paris    8.0    NaN     NaN  Python
7         108   Tom  24.0  Berlin    2.0   49.0     0.0  Python
8         109  Emma  22.0  Moscow    6.0   88.0     1.0      ML

In [189]:
full_df.shape

(9, 8)

In [190]:
full_df["city"].astype("category")

0    Moscow
1    Berlin
2    Moscow
3     Paris
4    Berlin
5    Moscow
6     Paris
7    Berlin
8    Moscow
Name: city, dtype: category
Categories (3, str): ['Berlin', 'Moscow', 'Paris']

In [191]:
full_df.dtypes

student_id      int64
name              str
age           float64
city              str
hours         float64
score         float64
passed        float64
course            str
dtype: object

In [192]:
full_df = pd.get_dummies(
    full_df,
    columns=["city", "course"],
    dtype=int
)
full_df

,student_id,name,age,hours,score,passed,city_Berlin,city_Moscow,city_Paris,course_ML,course_Python
0,101,Alex,19.0,4.0,72.0,1.0,0,1,0,1,0
1,102,Max,21.0,6.0,85.0,1.0,1,0,0,1,0
2,103,Anna,18.0,7.0,91.0,1.0,0,1,0,1,0
3,104,Kate,20.0,3.0,58.0,0.0,0,0,1,0,1
4,105,John,20.5,5.0,NaN,0.0,1,0,0,0,1
5,106,Mike,23.0,5.5,76.0,1.0,0,1,0,1,0
6,107,Lisa,19.0,8.0,NaN,NaN,0,0,1,0,1
7,108,Tom,24.0,2.0,49.0,0.0,1,0,0,0,1
8,109,Emma,22.0,6.0,88.0,1.0,0,1,0,1,0

In [194]:
full_df["passed"] = full_df["passed"].astype("boolean")
full_df

,student_id,name,age,hours,score,passed,city_Berlin,city_Moscow,city_Paris,course_ML,course_Python
0,101,Alex,19.0,4.0,72.0,True,0,1,0,1,0
1,102,Max,21.0,6.0,85.0,True,1,0,0,1,0
2,103,Anna,18.0,7.0,91.0,True,0,1,0,1,0
3,104,Kate,20.0,3.0,58.0,False,0,0,1,0,1
4,105,John,20.5,5.0,NaN,False,1,0,0,0,1
5,106,Mike,23.0,5.5,76.0,True,0,1,0,1,0
6,107,Lisa,19.0,8.0,NaN,<NA>,0,0,1,0,1
7,108,Tom,24.0,2.0,49.0,False,1,0,0,0,1
8,109,Emma,22.0,6.0,88.0,True,0,1,0,1,0

In [195]:
full_df["score_per_hour"] = full_df["score"] / full_df["hours"]

In [196]:
full_df

,student_id,name,age,hours,score,passed,city_Berlin,city_Moscow,city_Paris,course_ML,course_Python,score_per_hour
0,101,Alex,19.0,4.0,72.0,True,0,1,0,1,0,18.000000
1,102,Max,21.0,6.0,85.0,True,1,0,0,1,0,14.166667
2,103,Anna,18.0,7.0,91.0,True,0,1,0,1,0,13.000000
3,104,Kate,20.0,3.0,58.0,False,0,0,1,0,1,19.333333
4,105,John,20.5,5.0,NaN,False,1,0,0,0,1,NaN
5,106,Mike,23.0,5.5,76.0,True,0,1,0,1,0,13.818182
6,107,Lisa,19.0,8.0,NaN,<NA>,0,0,1,0,1,NaN
7,108,Tom,24.0,2.0,49.0,False,1,0,0,0,1,24.500000
8,109,Emma,22.0,6.0,88.0,True,0,1,0,1,0,14.666667