In [229]:
import pandas as pd 

students = pd.DataFrame({
    "name": ["Alex", "Max", "Anna", "Kate", "John"],
    "age": [19, 21, 18, 20, 22],
    "score": [72, 85, 91, 58, 67],
    "hours": [4, 6, 7, 3, 5],
    "passed": [1, 1, 1, 0, 0]
})

print(students)

print("\n",students.shape)
print("\n",students.columns)
print("\n",students.index)
print("\n",students.dtypes)

   name  age  score  hours  passed
0  Alex   19     72      4       1
1   Max   21     85      6       1
2  Anna   18     91      7       1
3  Kate   20     58      3       0
4  John   22     67      5       0

 (5, 5)

 Index(['name', 'age', 'score', 'hours', 'passed'], dtype='str')

 RangeIndex(start=0, stop=5, step=1)

 name        str
age       int64
score     int64
hours     int64
passed    int64
dtype: object

In [230]:
print(students["score"])
print(students["score"].dtype, students["score"].shape)

0    72
1    85
2    91
3    58
4    67
Name: score, dtype: int64
int64 (5,)

In [231]:
print(students[["age", "score"]])
print("\n", students[["age", "score"]].dtypes, students[["age", "score"]].shape)

   age  score
0   19     72
1   21     85
2   18     91
3   20     58
4   22     67

 age      int64
score    int64
dtype: object (5, 2)

In [232]:
print(students[["age"]])

   age
0   19
1   21
2   18
3   20
4   22

In [233]:
age = students["age"]
name = students["name"]

z = pd.Series(age.values, index = name.values)

print(z)

Alex    19
Max     21
Anna    18
Kate    20
John    22
dtype: int64

In [234]:
df = pd.read_csv("students.csv")

df.head()

   name  age  score  hours  passed
0  Alex   19     72      4       1
1   Max   21     85      6       1
2  Anna   18     91      7       1
3  Kate   20     58      3       0
4  John   22     67      5       0

In [235]:
df.tail(3)

   name  age  score  hours  passed
5  Mike   23     76      6       1
6  Lisa   19     88      7       1
7   Tom   24     49      2       0

In [236]:
print(students["score"])
print(students["score"].dtype, students["score"].shape)

0    72
1    85
2    91
3    58
4    67
Name: score, dtype: int64
int64 (5,)

In [237]:
print(students[["age", "score"]])
print("\n", students[["age", "score"]].dtypes, students[["age", "score"]].shape)

   age  score
0   19     72
1   21     85
2   18     91
3   20     58
4   22     67

 age      int64
score    int64
dtype: object (5, 2)

In [238]:
print(students[["age"]])

   age
0   19
1   21
2   18
3   20
4   22

In [239]:
df.shape

(8, 5)

In [240]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      str
 1   age     8 non-null      int64
 2   score   8 non-null      int64
 3   hours   8 non-null      int64
 4   passed  8 non-null      int64
dtypes: int64(4), str(1)
memory usage: 452.0 bytes

In [241]:
df.describe()

            age      score    hours    passed
count   8.00000   8.000000  8.00000  8.000000
mean   20.75000  73.250000  5.00000  0.625000
std     2.12132  14.829989  1.85164  0.517549
min    18.00000  49.000000  2.00000  0.000000
25%    19.00000  64.750000  3.75000  0.000000
50%    20.50000  74.000000  5.50000  1.000000
75%    22.25000  85.750000  6.25000  1.000000
max    24.00000  91.000000  7.00000  1.000000

In [242]:
df = pd.DataFrame({
    "name": ["Alex", "Max", "Anna", "Kate", "John", "Mike", "Lisa", "Tom"],
    "age": [19, 21, 18, 20, None, 23, 19, 24],
    "score": [72, 85, 91, 58, 67, None, 88, 49],
    "hours": [4, 6, 7, 3, 5, 6, None, 2],
    "city": [
        "Moscow", "Berlin", "Moscow", "Paris",
        "Berlin", "Moscow", "Paris", "Berlin"
    ],
    "passed": [1, 1, 1, 0, 0, 1, 1, 0]
})

df.head()

   name   age  score  hours    city  passed
0  Alex  19.0   72.0    4.0  Moscow       1
1   Max  21.0   85.0    6.0  Berlin       1
2  Anna  18.0   91.0    7.0  Moscow       1
3  Kate  20.0   58.0    3.0   Paris       0
4  John   NaN   67.0    5.0  Berlin       0

In [243]:
print(df.iloc[:3, :3])

   name   age  score
0  Alex  19.0   72.0
1   Max  21.0   85.0
2  Anna  18.0   91.0

In [244]:
print(df.loc[2:5, ["name", "score", "hours"]])

   name  score  hours
2  Anna   91.0    7.0
3  Kate   58.0    3.0
4  John   67.0    5.0
5  Mike    NaN    6.0

In [245]:
print(df[df["score"] >= 80])

   name   age  score  hours    city  passed
1   Max  21.0   85.0    6.0  Berlin       1
2  Anna  18.0   91.0    7.0  Moscow       1
6  Lisa  19.0   88.0    NaN   Paris       1

In [246]:
print(df[(df["score"] >= 70) & (df["age"] < 21)])

   name   age  score  hours    city  passed
0  Alex  19.0   72.0    4.0  Moscow       1
2  Anna  18.0   91.0    7.0  Moscow       1
6  Lisa  19.0   88.0    NaN   Paris       1

In [247]:
print(df[df["city"].isin(["Moscow", "Berlin"])])

   name   age  score  hours    city  passed
0  Alex  19.0   72.0    4.0  Moscow       1
1   Max  21.0   85.0    6.0  Berlin       1
2  Anna  18.0   91.0    7.0  Moscow       1
4  John   NaN   67.0    5.0  Berlin       0
5  Mike  23.0    NaN    6.0  Moscow       1
7   Tom  24.0   49.0    2.0  Berlin       0

In [248]:
print(df.loc[df["score"] >= 80, ["name", "score"]])

   name  score
1   Max   85.0
2  Anna   91.0
6  Lisa   88.0

In [249]:
df.isna().sum()

name      0
age       1
score     1
hours     1
city      0
passed    0
dtype: int64

In [250]:
df.tail(3)

   name   age  score  hours    city  passed
5  Mike  23.0    NaN    6.0  Moscow       1
6  Lisa  19.0   88.0    NaN   Paris       1
7   Tom  24.0   49.0    2.0  Berlin       0

In [251]:
print(students["score"])
print(students["score"].dtype, students["score"].shape)

0    72
1    85
2    91
3    58
4    67
Name: score, dtype: int64
int64 (5,)

In [252]:
print(students[["age", "score"]])
print("\n", students[["age", "score"]].dtypes, students[["age", "score"]].shape)

   age  score
0   19     72
1   21     85
2   18     91
3   20     58
4   22     67

 age      int64
score    int64
dtype: object (5, 2)

In [253]:
print(students[["age"]])

   age
0   19
1   21
2   18
3   20
4   22

In [254]:
df.shape

(8, 6)

In [255]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      str
 1   age     7 non-null      float64
 2   score   7 non-null      float64
 3   hours   7 non-null      float64
 4   city    8 non-null      str
 5   passed  8 non-null      int64
dtypes: float64(3), int64(1), str(2)
memory usage: 516.0 bytes

In [256]:
df.describe()

             age      score     hours    passed
count   7.000000   7.000000  7.000000  8.000000
mean   20.571429  72.857143  4.714286  0.625000
std     2.225395  15.973192  1.799471  0.517549
min    18.000000  49.000000  2.000000  0.000000
25%    19.000000  62.500000  3.500000  0.000000
50%    20.000000  72.000000  5.000000  1.000000
75%    22.000000  86.500000  6.000000  1.000000
max    24.000000  91.000000  7.000000  1.000000

In [257]:
df.loc[df["score"].isna()]

   name   age  score  hours    city  passed
5  Mike  23.0    NaN    6.0  Moscow       1

In [258]:
df_clean = df.copy()

df_clean["age"] = df_clean["age"].fillna(df_clean["age"].median())

In [259]:
df_clean.head(10)

   name   age  score  hours    city  passed
0  Alex  19.0   72.0    4.0  Moscow       1
1   Max  21.0   85.0    6.0  Berlin       1
2  Anna  18.0   91.0    7.0  Moscow       1
3  Kate  20.0   58.0    3.0   Paris       0
4  John  20.0   67.0    5.0  Berlin       0
5  Mike  23.0    NaN    6.0  Moscow       1
6  Lisa  19.0   88.0    NaN   Paris       1
7   Tom  24.0   49.0    2.0  Berlin       0

In [260]:
df_clean.dropna(subset = "score")

   name   age  score  hours    city  passed
0  Alex  19.0   72.0    4.0  Moscow       1
1   Max  21.0   85.0    6.0  Berlin       1
2  Anna  18.0   91.0    7.0  Moscow       1
3  Kate  20.0   58.0    3.0   Paris       0
4  John  20.0   67.0    5.0  Berlin       0
6  Lisa  19.0   88.0    NaN   Paris       1
7   Tom  24.0   49.0    2.0  Berlin       0

In [261]:
df = pd.DataFrame({
    "name": [
        "Alex", "Max", "Anna", "Kate",
        "John", "Alex", "Lisa", "Tom"
    ],
    "age": [
        19, 21, 18, 20,
        22, 19, 19, 24
    ],
    "score": [
        72, 85, 91, 58,
        67, 72, 88, 49
    ],
    "city": [
        "Moscow", "Berlin", "Moscow", "Paris",
        "Berlin", "Moscow", "Paris", "Berlin"
    ],
    "passed": [
        1, 1, 1, 0,
        0, 1, 1, 0
    ]
})

In [262]:
print(df.duplicated().sum())

1

In [263]:
print(df[df.duplicated()])

   name  age  score    city  passed
5  Alex   19     72  Moscow       1

In [264]:
df_clean = df[~df.duplicated()]
df_clean

   name  age  score    city  passed
0  Alex   19     72  Moscow       1
1   Max   21     85  Berlin       1
2  Anna   18     91  Moscow       1
3  Kate   20     58   Paris       0
4  John   22     67  Berlin       0
6  Lisa   19     88   Paris       1
7   Tom   24     49  Berlin       0

In [265]:
print(df.dtypes)

name        str
age       int64
score     int64
city        str
passed    int64
dtype: object

In [266]:
df["passed"] = df["passed"].astype(bool)
print(df.dtypes)

name        str
age       int64
score     int64
city        str
passed     bool
dtype: object

In [267]:
df_clean = df_clean.sort_values("score", ascending = False)
df_clean

   name  age  score    city  passed
2  Anna   18     91  Moscow       1
6  Lisa   19     88   Paris       1
1   Max   21     85  Berlin       1
0  Alex   19     72  Moscow       1
4  John   22     67  Berlin       0
3  Kate   20     58   Paris       0
7   Tom   24     49  Berlin       0

In [268]:
df.value_counts("city")

city
Moscow    3
Berlin    3
Paris     2
Name: count, dtype: int64

In [269]:
df.value_counts("city", normalize= True)

city
Moscow    0.375
Berlin    0.375
Paris     0.250
Name: proportion, dtype: float64

In [270]:
df.value_counts("passed")

passed
True     5
False    3
Name: count, dtype: int64

Нет сохранения в df
df отсортируеться но не сохраниться

In [279]:
import pandas as pd

df = pd.DataFrame({
    "city": ["Moscow", "Berlin", "Moscow", "Berlin", "Moscow"],
    "sales": [100, 200, 150, 300, 250],
    "clients": [10, 20, 15, 25, 30]
})

In [281]:
students = pd.DataFrame({
    "student_id": [1, 2, 3, 4, 5, 6],
    "name": ["Alex", "Max", "Anna", "Kate", "John", "Lisa"],
    "city": ["Moscow", "Berlin", "Moscow", "Paris", "Berlin", "Paris"],
    "age": [19, 21, 18, 20, 22, 19]
})

results = pd.DataFrame({
    "student_id": [1, 2, 3, 4, 5],
    "score": [72, 85, 91, 58, 67],
    "hours": [4, 6, 7, 3, 5]
})

In [ ]:
df_inner = students.merge(results, on="student_id", how = "inner")
df_inner.head()

   student_id  name    city  age  score  hours
0           1  Alex  Moscow   19     72      4
1           2   Max  Berlin   21     85      6
2           3  Anna  Moscow   18     91      7
3           4  Kate   Paris   20     58      3
4           5  John  Berlin   22     67      5

In [288]:
df_inner.shape

(5, 6)

In [295]:
df = students.merge(results, on="student_id", how = "left")
df

   student_id  name    city  age  score  hours
0           1  Alex  Moscow   19   72.0    4.0
1           2   Max  Berlin   21   85.0    6.0
2           3  Anna  Moscow   18   91.0    7.0
3           4  Kate   Paris   20   58.0    3.0
4           5  John  Berlin   22   67.0    5.0
5           6  Lisa   Paris   19    NaN    NaN

In [298]:
df.isna().sum()

student_id    0
name          0
city          0
age           0
score         1
hours         1
dtype: int64